'use client';

import { useForm } from 'react-hook-form';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { useTranslation } from 'react-i18next';
import { SolicitudFormData } from '@/types/solicitud.types';
import dynamic from 'next/dynamic';

const ClienteSearch = dynamic(() => import('./ClienteSearch'), {
  ssr: false,
  loading: () => (
    <div className="h-10 w-full bg-gray-200 rounded-md animate-pulse" />
  ),
});

export default function SolicitudForm() {
  const router = useRouter();
  const { t, i18n } = useTranslation();
  const [serverErrors, setServerErrors] = useState<Record<string, string>>({});
  const [submitting, setSubmitting] = useState(false);

  const {
    register,
    handleSubmit,
    setValue,
    watch,
    formState: { errors },
  } = useForm<SolicitudFormData>({
    defaultValues: {
      tipoViaje: 'turismo',
      estado: 'pendiente',
    },
  });

  const nombreCliente = watch('nombreCliente') || '';

  async function onSubmit(data: SolicitudFormData) {
    setSubmitting(true);
    setServerErrors({});

    try {
      const res = await fetch('http://localhost:3001/api/solicitudes', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(data),
      });

      const json = await res.json();

      if (!res.ok) {
        if (json.fields) {
          setServerErrors(json.fields);
        }
        return;
      }

      router.push('/solicitudes');
    } catch {
      setServerErrors({ general: t('form.connectionError') });
    } finally {
      setSubmitting(false);
    }
  }

  const inputClass = (field: string) =>
    `w-full px-3 py-2 border rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none ${
      errors[field as keyof SolicitudFormData] || serverErrors[field]
        ? 'border-red-500'
        : 'border-gray-300'
    }`;

  function fieldError(field: string) {
    const clientErr = errors[field as keyof SolicitudFormData]?.message;
    const serverErr = serverErrors[field];
    const msg = clientErr || serverErr;
    return msg ? <p className="text-red-600 text-sm mt-1">{msg}</p> : null;
  }

  return (
    <form key={i18n.language} onSubmit={handleSubmit(onSubmit)} className="space-y-5">
      {serverErrors.general && (
        <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-md">
          {serverErrors.general}
        </div>
      )}

      {/* ID Solicitud */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          {t('form.idSolicitud')}
        </label>
        <input
          type="text"
          disabled
          value={t('form.autoGenerated')}
          className="w-full px-3 py-2 border border-gray-200 rounded-md bg-gray-100 text-gray-500"
        />
      </div>

      {/* DNI */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          {t('form.dni')}
        </label>
        <input
          type="text"
          {...register('dni', {
            required: t('validation.dniRequired'),
            pattern: {
              value: /^\d{1,2}\.?\d{3}\.?\d{3}-[\dkK]$/,
              message: t('validation.dniFormat'),
            },
          })}
          placeholder={t('form.dniPlaceholder')}
          className={inputClass('dni')}
        />
        {fieldError('dni')}
      </div>

      {/* Nombre Cliente */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          {t('form.nombreCliente')}
        </label>
        <input type="hidden" {...register('nombreCliente', { required: t('validation.nombreRequired') })} />
        <ClienteSearch
          value={nombreCliente}
          onChange={(nombre, cliente) => {
            setValue('nombreCliente', nombre, { shouldValidate: true });
            if (cliente) {
              setValue('dni', cliente.dni, { shouldValidate: true });
              setValue('emailCliente', cliente.email, { shouldValidate: true });
            }
          }}
          error={errors.nombreCliente?.message || serverErrors.nombreCliente}
        />
      </div>

      {/* Email */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          {t('form.emailCliente')}
        </label>
        <input
          type="text"
          {...register('emailCliente', {
            required: t('validation.emailRequired'),
            pattern: {
              value: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
              message: t('validation.emailFormat'),
            },
          })}
          placeholder={t('form.emailPlaceholder')}
          className={inputClass('emailCliente')}
        />
        {fieldError('emailCliente')}
      </div>

      {/* Origen */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          {t('form.origen')}
        </label>
        <input
          type="text"
          {...register('origen', { required: t('validation.origenRequired') })}
          placeholder={t('form.origenPlaceholder')}
          className={inputClass('origen')}
        />
        {fieldError('origen')}
      </div>

      {/* Destino */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          {t('form.destino')}
        </label>
        <input
          type="text"
          {...register('destino', { required: t('validation.destinoRequired') })}
          placeholder={t('form.destinoPlaceholder')}
          className={inputClass('destino')}
        />
        {fieldError('destino')}
      </div>

      {/* Tipo de Viaje */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          {t('form.tipoViaje')}
        </label>
        <select
          {...register('tipoViaje')}
          className={inputClass('tipoViaje')}
        >
          <option value="negocios">{t('form.tipoNegocios')}</option>
          <option value="turismo">{t('form.tipoTurismo')}</option>
          <option value="otros">{t('form.tipoOtros')}</option>
        </select>
        {fieldError('tipoViaje')}
      </div>

      {/* Fecha Salida */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          {t('form.fechaSalida')}
        </label>
        <input
          type="datetime-local"
          {...register('fechaSalida', { required: t('validation.fechaSalidaRequired') })}
          className={inputClass('fechaSalida')}
        />
        {fieldError('fechaSalida')}
      </div>

      {/* Fecha Regreso */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          {t('form.fechaRegreso')}
        </label>
        <input
          type="datetime-local"
          {...register('fechaRegreso', {
            required: t('validation.fechaRegresoRequired'),
            validate: (value) => {
              const salida = watch('fechaSalida');
              if (salida && value && new Date(value) <= new Date(salida)) {
                return t('validation.fechaRegresoAfter');
              }
              return true;
            },
          })}
          className={inputClass('fechaRegreso')}
        />
        {fieldError('fechaRegreso')}
      </div>

      {/* Fecha Registro */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">
          {t('form.fechaRegistro')}
        </label>
        <input
          type="text"
          disabled
          value={t('form.autoRegistered')}
          className="w-full px-3 py-2 border border-gray-200 rounded-md bg-gray-100 text-gray-500"
        />
      </div>

      {/* Estado */}
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-2">
          {t('form.estado')}
        </label>
        <div className="flex gap-6">
          <label className="flex items-center gap-2 cursor-pointer">
            <input type="radio" value="pendiente" {...register('estado')} className="text-blue-600" />
            <span className="text-sm">{t('form.pendiente')}</span>
          </label>
          <label className="flex items-center gap-2 cursor-pointer">
            <input type="radio" value="en proceso" {...register('estado')} className="text-blue-600" />
            <span className="text-sm">{t('form.enProceso')}</span>
          </label>
          <label className="flex items-center gap-2 cursor-pointer">
            <input type="radio" value="finalizada" {...register('estado')} className="text-blue-600" />
            <span className="text-sm">{t('form.finalizada')}</span>
          </label>
        </div>
        {fieldError('estado')}
      </div>

      <button
        type="submit"
        disabled={submitting}
        className="w-full bg-blue-600 text-white py-3 rounded-md font-semibold hover:bg-blue-700 transition-colors disabled:opacity-50"
      >
        {submitting ? t('form.submitting') : t('form.submit')}
      </button>
    </form>
  );
}
